# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: smellems Solutions
  fr: smellems Solutions
description:
  en: Support for open source software and open standards in Gatineau, Québec, Ottawa, Ontario.
  fr: Support pour logiciels libres et normes ouvertes à Gatineau, Québec, Ottawa, Ontario.
index:
  en:
  fr: accueil.html
language:
  en: English
  fr: Français
home:
  en: Home
  fr: Accueil
home_link:
  en: index.html
  fr: accueil.html
about:
  en: About
  fr: À propos
about_link:
  en: about.html
  fr: apropos.html
subtitle:
  en: Open Source Software & Open Standards
  fr: Logiciels libres & normes ouvertes
learnmore:
  en: Learn more
  fr: En savoir plus

email: info@smellems.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://smellems.github.io" # the base hostname & protocol for your site
twitter_username: smellems
github_username: smellems

# Build settings
markdown: kramdown
